### ISSUE TITLE
Repository name update

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/fifa-potential#10]
We need to have our repo name reflect the project in some way according to the milestone requirements. 

How does `2023_dsci522-group17_fifa-potential` sound? 
Or just `2023_dsci522_fifa-potential`? 

We'll also have to update our URLs in the README :/

**Comment by WaleedMahmood1** [comment]
You are right! I think the first one `2023_dsci522-group17_fifa-potential` sounds good. It includes the number of our group and reflects our project. 

Side note: just some food for thought - maybe once we have completed 522, we could remove `2023_dsci522_group17` because we might be looking to use this as a project for our portfolios...

**Comment by meretelutz** [comment]
Is there a reason why we can't have it just as fifa-potential? Tiff's repository was called breast_cancer_predictor so I think it's okay if we're pretty concise. It would also make it look less like a school project if we wanted it for our portfolios.

**Comment by srfrew** [comment]
Let’s just go with fifa-potential! I’ll make the change once we are close to finished
