### ISSUE TITLE
Jupyter Book Integration

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/fifa-potential#34]
Issue for discussion and resources for jupyter book update for Milestone 3
https://jupyterbook.org/en/stable/intro.html

- [x] render to `html` or `pdf`
- [x] bibliography
- [x] automatic numbering of figures / tables 
- [x] inline code rendering

**Comment by meretelutz** [comment]
I just made a branch for this, will start working on it now!

**Comment by WaleedMahmood1** [comment]
Thanks for creating the issue Simon.
Just for everyone's ease these are the commands to render the report and then copy the build folder contents into docs/ so that we can configure GitHub to render the page from the docs folder:
`jupyter-book build report`
`cp -r report/_build/html/* docs`

**Comment by srfrew** [comment]
@WaleedMahmood1 am I correct in thinking that the final `.ipynb`, `.html`, and `.pdf` files are going to end up in `docs/`?

Just wanting to update the readme at some point

**Comment by WaleedMahmood1** [comment]
@srfrew So following what Tiffany has done with her repo, the `.ipynb`, `.pdf` files will be in the report folder, along with a copy of the`.html` file. 
But the files that render after we run `jupyter-book build report` from the root of our project directory, the files created in the report folder under `_build/html/` will need to be transferred to the `docs/` folder in the root of our project, so that we can configure GitHub to render the github pages for the `.html` files created.
Hope that makes sense.

**Comment by srfrew** [comment]
Okay great that makes sense, thanks for the clarification!

**Comment by WaleedMahmood1** [comment]
I have created the `references.bib` file and added the `{bibliography}` code cell in the `.ipynb` file as well, in the `reference_bibtex` branch and it is ready to be merged. If someone could review and do that, that would be great. Thanks!

@meretelutz How are you doing on the other objectives?

**Comment by meretelutz** [comment]
Still working on the notebook. It was tricky to figure out but I think i've got it now. Just trying to fix the way some of the tables look right now. I'm worried we're going to have a lot of merge conflicts though 🫣 I had to change a lot of the file structure to get the book to work

**Comment by WaleedMahmood1** [comment]
Awesome. I am heading to ubc right now. Once you are done, we can merge and resolve any conflicts together, since you would have a better idea of what goes where. 
The pull request isn't showing any merge conflicts for now haha

**Comment by meretelutz** [comment]
Ok I created a pull request and solved a lot of the merge conflicts, so I think we're good to go! But please double check! The new report is under the report file. I don't really get what file structure you guys were talking about but feel free to change if what I have isn't right

**Comment by WaleedMahmood1** [comment]
Perfect. I will check it out in a bit. Thanks!

**Comment by meretelutz** [comment]
Just added a note under my pull request - but I forgot to add the bibliography changes to my commit! It didn't pop up when i was dealing with merge conflicts because I moved the file from its original location so there were two versions. And I accidentally deleted the old report before my last commit. So we need to roll that back before completing the pull request

**Comment by WaleedMahmood1** [comment]
It's not a problem! I will check it out. It was only one change at the end where I added a new cell for the bibliography. I can do that again

**Comment by meretelutz** [comment]
Oh okay that's not too bad then. But we have to incorporate the in-text citations as well, right? Have you done that part yet?

**Comment by WaleedMahmood1** [comment]
I hadn't done them yet, wanted to do them after all formatting and text had been finalised, just incase haha. 
I am going to merge your branch now to main and then pull the changes to the `reference_bibtex` branch. I'll add the citations and then re-render the jupyter book and then create another pull request.

**Comment by WaleedMahmood1** [comment]
@meretelutz I pulled/merged in your changes on the `jupyter-book-integration` branch onto the `reference_bibtex` branch directly without merging with the main branch in case `jupyter-book-integration` was not yet ready to be merged. 

I don't think it should cause any issues if `jupyter-book-integration` is merged with main and then `reference_bibtex` is merged with main, since the two branches do not have any merge conflicts with eachother.

**Comment by WaleedMahmood1** [comment]
I installed the `jupyter-book=0.15.1` library on my local repo to get the `jupyter-book build report` command to work. So I have added it into the `environment.yml` file too and then recreated another conda environment using this new environment file and rendered the jupyter notebook again and it works. If others could also check just to be sure

**Comment by srfrew** [comment]
I can check!

**Comment by srfrew** [comment]
Alright, so I needed to update the `how_to_evaluate_soccer_players` bib reference, but otherwise things built on my end! I'm looking at copying that or setting the output to go to our docs folder automatically

**Comment by srfrew** [comment]
I have updated the readme with instructions for building the report! 

I have also cleaned up the extra outputs from the README .html 

Finally the in-text values like best CV performance, best hyperparameters, and best test scores are glued to variables and will auto-update

**Comment by meretelutz** [comment]
Closing this issue as we have finalized our jupyter book
